import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import YAML from "yaml";

type MetadataValidation = {
  type: string;
  arg?: unknown;
};

type MetadataField = {
  name: string;
  type: string;
  valuetype?: string;
  choices?: string[];
  default?: unknown;
  summary?: string | undefined;
  description?: string | undefined;
  // A bare `validations:` key parses as null rather than absent.
  validations?: MetadataValidation[] | null;
};

type MetadataGroup = {
  name: string;
  title?: string;
  type?: string;
  summary?: string | undefined;
  description?: string | undefined;
  fields?: MetadataField[];
};

export type MetadataFile = {
  groups: MetadataGroup[];
};

/**
 * The samplers that may appear nested under a rule via `Rules.Sampler` are
 * listed in the metadata itself (the `validChildren` validation); the full
 * set allowed at the top level of the `Samplers` map is every sampler group.
 */
const RULES_GROUP_TYPE_NAMES: Record<string, string> = {
  Rules: "RulesBasedSamplerRule",
  Conditions: "RulesBasedSamplerCondition",
};

/**
 * Structural field types the flat metadata can't express: which object type an
 * `object`/`objectarray`/`sliceorscalar` field actually holds. Keyed by
 * `<group>.<field>`. `Rules.Sampler` is handled separately via `validChildren`.
 */
const STRUCTURAL_FIELD_TYPES: Record<string, string> = {
  "RulesBasedSampler.Rules": "RulesBasedSamplerRule[]",
  "Rules.Conditions": "RulesBasedSamplerCondition[]",
  "Conditions.Value":
    "string | number | boolean | Array<string | number | boolean>",
};

const metadataDirectory = new URL("../config/metadata/", import.meta.url);
const output = new URL("./index.d.ts", import.meta.url);

export function generateRefineryConfigTypes(): string {
  const configMeta = readMetadata("configMeta.yaml");
  const rulesMeta = readMetadata("rulesMeta.yaml");
  const hash = createHash("sha256");
  for (const name of ["configMeta.yaml", "rulesMeta.yaml"]) {
    hash
      .update(name)
      .update("\0")
      .update(readFileSync(new URL(name, metadataDirectory)));
  }
  return [
    `// Generated by npm run generate. Do not edit.\n// Source: config/metadata/{configMeta,rulesMeta}.yaml\n// Metadata SHA-256: ${hash.digest("hex")}`,
    generateConfigTypes(configMeta),
    generateRulesTypes(rulesMeta),
    "",
  ].join("\n\n");
}

function readMetadata(filename: string): MetadataFile {
  const raw: unknown = YAML.parse(
    readFileSync(new URL(filename, metadataDirectory), "utf8"),
  );
  // Validate the portion of the metadata consumed here; additional documentation
  // and runtime-validation keys remain owned by Refinery.
  if (
    !raw ||
    typeof raw !== "object" ||
    !("groups" in raw) ||
    !Array.isArray(raw.groups)
  ) {
    throw new Error(`Invalid metadata groups in ${filename}`);
  }
  if (!raw.groups.every(isMetadataGroup)) {
    throw new Error(`Invalid metadata group or field in ${filename}`);
  }
  return { groups: raw.groups };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function optionalStrings(
  value: Record<string, unknown>,
  names: string[],
): boolean {
  return names.every(
    (name) => value[name] === undefined || typeof value[name] === "string",
  );
}

function isMetadataField(value: unknown): value is MetadataField {
  return (
    isRecord(value) &&
    typeof value.name === "string" &&
    typeof value.type === "string" &&
    optionalStrings(value, ["valuetype", "summary", "description"]) &&
    (value.choices === undefined ||
      (Array.isArray(value.choices) &&
        value.choices.every((choice) => typeof choice === "string"))) &&
    (value.validations == null ||
      (Array.isArray(value.validations) &&
        value.validations.every(
          (validation) =>
            isRecord(validation) && typeof validation.type === "string",
        )))
  );
}

function isMetadataGroup(value: unknown): value is MetadataGroup {
  return (
    isRecord(value) &&
    typeof value.name === "string" &&
    optionalStrings(value, ["title", "type", "summary", "description"]) &&
    (value.fields === undefined ||
      (Array.isArray(value.fields) && value.fields.every(isMetadataField)))
  );
}

function generateConfigTypes(meta: MetadataFile): string {
  const sections: string[] = [];
  const rootFields: string[] = [];

  for (const group of meta.groups) {
    const typeName = `${group.name}Config`;
    sections.push(generateGroupType({ group, typeName }));
    rootFields.push(
      [
        jsdoc({ summary: group.summary, description: group.description }),
        `\t${group.name}${group.fields?.some((field) => field.validations?.some((validation) => validation.type === "required")) ? "" : "?"}: ${typeName}`,
      ]
        .filter(Boolean)
        .join("\n"),
    );
  }

  sections.push(
    [
      jsdoc({
        summary: "is the root of a Refinery config.yaml file.",
        description:
          "Groups containing globally required fields must be present; other groups use Refinery defaults.",
      }),
      `export type RefineryConfig = {`,
      rootFields.join("\n"),
      `}`,
    ].join("\n"),
  );

  return sections.join("\n\n");
}

function generateRulesTypes(meta: MetadataFile): string {
  const sections: string[] = [];
  const samplerGroupNames: string[] = [];
  let samplersGroup: MetadataGroup | undefined;
  let downstreamSamplerNames: string[] = [];

  for (const group of meta.groups) {
    if (group.type === "samplerList") {
      samplersGroup = group;
      continue;
    }

    if (group.name.endsWith("Sampler")) {
      samplerGroupNames.push(group.name);
    }

    const samplerField = group.fields?.find(
      (field) => field.name === "Sampler",
    );
    const validChildren = samplerField?.validations?.find(
      (validation) => validation.type === "validChildren",
    )?.arg;
    if (Array.isArray(validChildren)) {
      downstreamSamplerNames = validChildren.map(String);
    }

    const typeName = RULES_GROUP_TYPE_NAMES[group.name] ?? group.name;
    sections.push(generateGroupType({ group, typeName }));
  }

  if (samplerGroupNames.length === 0 || downstreamSamplerNames.length === 0) {
    throw new Error(
      "rulesMeta.yaml is missing sampler groups or the Rules.Sampler validChildren list",
    );
  }

  const singleKey = (name: string, names: string[]) =>
    `{ ${names.map((key) => (key === name ? `${key}: ${key}` : `${key}?: never`)).join("; ")} }`;

  sections.push(
    [
      jsdoc({
        summary:
          "is a sampler allowed as the downstream `Sampler` of a rules-based sampler rule.",
        description:
          "Derived from the `validChildren` validation on `Rules.Sampler` in rulesMeta.yaml.",
      }),
      `export type RulesBasedDownstreamSampler =`,
      downstreamSamplerNames
        .map((name) => `\t| ${singleKey(name, samplerGroupNames)}`)
        .join("\n"),
    ].join("\n"),
  );

  sections.push(
    [
      jsdoc({
        summary:
          "is the sampler configuration for a single target (Honeycomb environment).",
        description:
          "Exactly one sampler type must be set per target; other sampler keys are explicitly forbidden in each union member.",
      }),
      `export type RefinerySamplerChoice =`,
      samplerGroupNames
        .map((name) => `\t| ${singleKey(name, samplerGroupNames)}`)
        .join("\n"),
    ].join("\n"),
  );

  sections.push(
    [
      jsdoc({
        summary: "is the root of a Refinery rules.yaml file.",
        description: samplersGroup?.description,
      }),
      `export type RefineryRules = {`,
      `\tRulesVersion: 2`,
      `\tSamplers: { __default__: RefinerySamplerChoice } & Record<`,
      `\t\tstring,`,
      `\t\tRefinerySamplerChoice`,
      `\t>`,
      `}`,
    ].join("\n"),
  );

  return sections.join("\n\n");
}

function generateGroupType(args: {
  group: MetadataGroup;
  typeName: string;
}): string {
  const { group, typeName } = args;
  const lines: string[] = [];

  const groupDoc = jsdoc({
    summary: group.summary ?? group.title,
    description: group.description,
  });
  if (groupDoc) {
    lines.push(groupDoc);
  }

  lines.push(`export type ${typeName} = {`);
  for (const field of group.fields ?? []) {
    const fieldDoc = jsdoc({
      summary: field.summary,
      description: field.description,
      default: field.default,
    });
    if (fieldDoc) {
      lines.push(indent(fieldDoc));
    }
    const optional = isRequired(field) ? "" : "?";
    lines.push(`\t${field.name}${optional}: ${fieldType({ group, field })}`);
  }
  lines.push(`}`);
  const constraints = new Set<string>();
  for (const field of group.fields ?? []) {
    for (const validation of field.validations ?? []) {
      if (
        validation.type !== "conflictsWith" &&
        validation.type !== "requiredWith"
      )
        continue;
      const other = validation.arg;
      if (
        typeof other !== "string" ||
        !group.fields?.some((candidate) => candidate.name === other)
      ) {
        throw new Error(
          `Invalid ${validation.type} reference for ${group.name}.${field.name}`,
        );
      }
      if (validation.type === "conflictsWith") {
        const [left, right] = [field.name, other].sort();
        constraints.add(` & ({ ${left}?: never } | { ${right}?: never })`);
      } else if (field.default === undefined) {
        // Runtime validation accepts a missing dependent field when it has a default.
        constraints.add(
          ` & ({ ${other}?: never } | { ${field.name}: ${fieldType({ group, field })} })`,
        );
      }
    }
  }
  lines.push(...constraints);

  return lines.join("\n");
}

function isRequired(field: MetadataField): boolean {
  return (
    field.validations?.some(
      (validation) =>
        validation.type === "required" || validation.type === "requiredInGroup",
    ) ?? false
  );
}

function fieldType(args: {
  group: MetadataGroup;
  field: MetadataField;
}): string {
  const { group, field } = args;

  const structural = STRUCTURAL_FIELD_TYPES[`${group.name}.${field.name}`];
  if (structural) {
    return structural;
  }

  if (group.name === "Rules" && field.name === "Sampler") {
    return "RulesBasedDownstreamSampler";
  }

  if (field.choices?.length) {
    return field.choices.map((choice) => JSON.stringify(choice)).join(" | ");
  }

  switch (field.type) {
    case "int":
    case "float":
    case "percentage":
      return "number";
    case "bool":
    case "defaulttrue":
      return "boolean";
    case "string":
    case "duration":
    case "hostport":
    case "url":
      return "string";
    case "memorysize":
      return "string | number";
    case "stringarray":
      return "string[]";
    case "map":
      return "Record<string, string>";
    default:
      throw new Error(
        `Unhandled metadata field type "${field.type}" for ${group.name}.${field.name}. ` +
          `Add a mapping in config-types/generate.ts.`,
      );
  }
}

function jsdoc(args: {
  summary?: string | undefined;
  description?: string | undefined;
  default?: unknown;
}): string {
  const bodyLines: string[] = [];
  if (args.summary) {
    bodyLines.push(...wrapText(args.summary.trim()));
  }
  if (args.description) {
    if (bodyLines.length) {
      bodyLines.push("");
    }
    for (const paragraph of args.description.trim().split(/\n{2,}/)) {
      if (bodyLines.length && bodyLines[bodyLines.length - 1] !== "") {
        bodyLines.push("");
      }
      bodyLines.push(...wrapText(paragraph.replaceAll(/\s+/g, " ").trim()));
    }
  }
  if (args.default !== undefined && args.default !== "") {
    if (bodyLines.length) {
      bodyLines.push("");
    }
    bodyLines.push(`@default ${JSON.stringify(args.default)}`);
  }

  if (bodyLines.length === 0) {
    return "";
  }

  return [
    "/**",
    ...bodyLines.map((line) => ` * ${line}`.trimEnd()),
    " */",
  ].join("\n");
}

function wrapText(text: string, width = 76): string[] {
  // Comment terminators inside metadata descriptions would break the JSDoc.
  const safe = text.replaceAll("*/", "*\\/");
  const words = safe.split(" ");
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    if (current && current.length + 1 + word.length > width) {
      lines.push(current);
      current = word;
    } else {
      current = current ? `${current} ${word}` : word;
    }
  }
  if (current) {
    lines.push(current);
  }
  return lines;
}

function indent(block: string): string {
  return block
    .split("\n")
    .map((line) => `\t${line}`)
    .join("\n");
}

const generated = generateRefineryConfigTypes();
if (process.argv.includes("--check")) {
  if (readFileSync(output, "utf8") !== generated) {
    throw new Error(
      "Generated Refinery types are stale. Run npm run generate.",
    );
  }
} else {
  writeFileSync(output, generated);
  console.log(`Generated ${fileURLToPath(output)}`);
}
